fiancee(Fiancee, 'Ronald Phillips').
stepfather(Stepfather, 'Ronald Phillips').
husband(Husband, 'Anna Roberts').
child('Evelyn Gray', Child).
fiance(Fiance, 'Wanda Young').
son(Son, 'Edward Cook').
brother_in_law(BInLaw, 'Dennis Ramirez').
father_in_law(FInLaw, 'Brian Cook').
meternal_grandparent(MGP, 'Edward Cook').
great_grandchild(GGC, 'Kelly Thomas').
great_grandchild(GGC, 'Phillip Thomas').
sister(Sister, 'Morrison Howard').
aunt(Person, 'Edward Cook').
cousin(Person, 'Teresa Howard').
grandson(GS, 'Stephen Howard').
sister_in_law(SInLaw, 'Andrew Gray').
stepdaughter(StepChild, 'Beverly Cook').
stepson(StepChild, 'Emily Flores').
wife(Person, 'Stephen Howard').
grandparent(GP, 'Eric Green').
